platform :ios, '8.0'
use_frameworks!

target 'បទចំរៀងរបស់ខ្ញុំ' do
    project 'NhacCuaTui.xcodeproj'
    pod 'GoogleAPIClient/Drive', '~> 1.0.2'
    pod 'GTMOAuth2', '~> 1.1.0'
    pod 'Alamofire', '~> 4.4'
    pod 'SDWebImage', '~> 4.0'
end
